In [1]:
import warnings
import matplotlib.pyplot as plt

import cv2
from dataset import TrainDataset, TestDataset
from skimage.feature import SIFT,hog
warnings.filterwarnings('ignore')
train_dataset = TrainDataset(transform=None)
test_dataset = TestDataset(transform=None)

/home/disk3/cbq/anaconda3/envs/drug/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [24]:
from skimage.feature import hog
import numpy as np
features = []
sift = cv2.SIFT.create(100)
for i in range(3):
    img = cv2.cvtColor(test_dataset[i],cv2.COLOR_RGB2GRAY)
    kp, des = sift.detectAndCompute(img,None)
    #features.append(hog(img))
    features.append(np.resize(des.reshape(-1),12800))
    

In [25]:
print(np.array(features))

[[18.  4. 23. ... 37.  1.  2.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [29.  6. 15. ...  0.  0.  0.]]


In [26]:
features = np.array(features)
features.shape

(3, 12800)

In [146]:
import numpy as np
a = np.array(features)
b = np.array(np.resize(a[0],(72900))).reshape(1,-1)
for i in range(3):
    a[i] = np.resize(a[i],(1,72900))
    if i != 0:
        b = np.append(b,a[i],axis=0)
print(b.shape)

(4, 72900)
